### ISSUE TITLE
`height` and `width` mixed up

### ISSUE THREAD

**Issue by sompylasar** [jonschlinkert/window-size#4]
https://nodejs.org/api/tty.html#tty_ws_columns
https://github.com/jonschlinkert/window-size/blob/master/index.js#L24-L25
```
    } else if (process.stdout.columns && process.stdout.rows) {
      height = process.stdout.columns;
      width = process.stdout.rows;
    }
```

`width` should be assigned from `columns`, `height` should be assigned from `rows`.

**Comment by jonschlinkert** [comment]
fixed in 0.2.0, fwiw I would have published a patch, but given how much this is downloaded it's highly possible if not likely that this change would break someone's code. 

thanks for the issue

**Comment by sompylasar** [comment]
thanks! actually, your code inspired [this code](https://github.com/AriaMinaei/RenderKid/blob/master/src/tools.coffee#L75-L76) which has got the bug copied: https://github.com/AriaMinaei/RenderKid/issues/5 -- and `RenderKid` is used as a dependency for the library called `pretty-error` which cleans and beautifies error stack traces for the console.

**Comment by jonschlinkert** [comment]
you sure about that? If it was I guess that's too bad lol, I don't see any acknowledgements or references to this lib, which is now fixed and would have fixed that lib too with a patch bump ;)

**Comment by sompylasar** [comment]
There is a comment at the top of the function:
```
  getCols: ->
    # Based on https://github.com/jonschlinkert/window-size
```
And that's lol too bad, of course. :100:

**Comment by jonschlinkert** [comment]
damn! lol nice catch though. I was of course saying that tongue-in-cheek, but it would have been nice to not be "officially" responsible for breaking their code lol

**Comment by sompylasar** [comment]
@jonschlinkert if they had your library as a dependency, you would be responsible, but currently this is not the case -- they should have read what they copy-paste.

**Comment by jonschlinkert** [comment]
I was jk, lol. no worries though, thanks!
